### ISSUE TITLE
Compatibility with fastavro 0.19.7

### ISSUE THREAD

**Issue by The-Fonz** [rmax/dask-avro#4]
`fastavro` seems to have changed one of their internal methods, `fastavro._read._iter_avro`, into `fastavro._read._iter_avro_{blocks,records}`. This seems to have happened in their latest minor release, from 0.19.6 to 0.19.7, see [this commit](https://github.com/fastavro/fastavro/commit/e0b8f1da3026dc218f9387cd62addcfae8683bce).

So a quick fix is just to install `fastavro==0.19.6` with conda or pip.

I'm not very familliar with `fastavro` or `dask-avro`, what would be a good solution?
- Pinning the dependency to `fastavro<=0.19.6`
- Handling it in `src/dask_avro/compat.py`
- Relying on public interface instead of internal methods?

**Comment by rmax** [comment]
Thank you for the report.

Due to #2, I suggested to expose the private method https://github.com/fastavro/fastavro/issues/162#issuecomment-365091398

Meanwhile I will pin the version to `<=0.19.6`.

Unrelated, I'm not sure why the [periodic build](https://travis-ci.org/rmax/dask-avro/jobs/392542503) pick `fastavro==0.17.10`. Caching probably?

**Comment by rmax** [comment]
Released version with `fastavro<=0.19.6` pinning: https://pypi.org/project/dask-avro/0.2.1/

**Comment by rmax** [comment]
Compatibility fixed ([commit](https://github.com/rmax/dask-avro/commit/47bbe18512caa5062cb1a9916f3225afc73eccc9)) in latest release https://pypi.org/project/dask-avro/
